import { WeatherData } from '../types/weather';
import { Location } from '../types/location';

export const mockLocations: Location[] = [
  {
    id: 'new-york',
    name: 'New York',
    country: 'US',
    lat: 40.7128,
    lon: -74.0060,
    lastCondition: 'Partly cloudy',
  },
  {
    id: 'london',
    name: 'London',
    country: 'UK',
    lat: 51.5074,
    lon: -0.1278,
    lastCondition: 'Rainy',
  },
  {
    id: 'tokyo',
    name: 'Tokyo',
    country: 'Japan',
    lat: 35.6762,
    lon: 139.6503,
    lastCondition: 'Clear',
  },
  {
    id: 'sydney',
    name: 'Sydney',
    country: 'Australia',
    lat: -33.8688,
    lon: 151.2093,
    lastCondition: 'Sunny',
  },
  {
    id: 'paris',
    name: 'Paris',
    country: 'France',
    lat: 48.8566,
    lon: 2.3522,
    lastCondition: 'Cloudy',
  },
  {
    id: 'berlin',
    name: 'Berlin',
    country: 'Germany',
    lat: 52.5200,
    lon: 13.4050,
    lastCondition: 'Partly cloudy',
  },
  {
    id: 'rome',
    name: 'Rome',
    country: 'Italy',
    lat: 41.9028,
    lon: 12.4964,
    lastCondition: 'Sunny',
  },
  {
    id: 'dubai',
    name: 'Dubai',
    country: 'UAE',
    lat: 25.2048,
    lon: 55.2708,
    lastCondition: 'Hot',
  },
];

export const mockWeatherData: WeatherData = {
  current: {
    temperature: 72,
    feelsLike: 74,
    condition: 'Partly cloudy',
    humidity: 65,
    windSpeed: 8,
    windDirection: 'NE',
    precipitation: 15,
    pressure: 1012,
    visibility: 10,
    uvIndex: 4,
    sunrise: '6:43 AM',
    sunset: '7:21 PM',
    lastUpdated: '10 mins ago',
    alerts: [
      {
        title: 'Thunderstorm Watch',
        description: 'Possible thunderstorms in the evening',
        severity: 'moderate',
      },
    ],
    airQuality: {
      index: 3,
      description: 'Good',
    },
  },
  forecast: {
    daily: [
      {
        date: '2025-04-10',
        maxTemp: 74,
        minTemp: 62,
        condition: 'Partly cloudy',
        humidity: 65,
        windSpeed: 8,
        precipitation: 15,
        uvIndex: 4,
        hourly: [
          { time: '12 AM', temp: 65, condition: 'Clear' },
          { time: '3 AM', temp: 63, condition: 'Clear' },
          { time: '6 AM', temp: 62, condition: 'Partly cloudy' },
          { time: '9 AM', temp: 67, condition: 'Partly cloudy' },
          { time: '12 PM', temp: 72, condition: 'Partly cloudy' },
          { time: '3 PM', temp: 74, condition: 'Partly cloudy' },
          { time: '6 PM', temp: 70, condition: 'Partly cloudy' },
          { time: '9 PM', temp: 67, condition: 'Partly cloudy' },
        ],
      },
      {
        date: '2025-04-11',
        maxTemp: 76,
        minTemp: 64,
        condition: 'Cloudy',
        humidity: 70,
        windSpeed: 7,
        precipitation: 30,
        uvIndex: 3,
        hourly: [
          { time: '12 AM', temp: 66, condition: 'Partly cloudy' },
          { time: '3 AM', temp: 65, condition: 'Partly cloudy' },
          { time: '6 AM', temp: 64, condition: 'Cloudy' },
          { time: '9 AM', temp: 68, condition: 'Cloudy' },
          { time: '12 PM', temp: 73, condition: 'Cloudy' },
          { time: '3 PM', temp: 76, condition: 'Cloudy' },
          { time: '6 PM', temp: 72, condition: 'Cloudy' },
          { time: '9 PM', temp: 69, condition: 'Cloudy' },
        ],
      },
      {
        date: '2025-04-12',
        maxTemp: 78,
        minTemp: 65,
        condition: 'Rainy',
        humidity: 80,
        windSpeed: 10,
        precipitation: 70,
        uvIndex: 2,
        hourly: [
          { time: '12 AM', temp: 68, condition: 'Cloudy' },
          { time: '3 AM', temp: 66, condition: 'Cloudy' },
          { time: '6 AM', temp: 65, condition: 'Cloudy' },
          { time: '9 AM', temp: 69, condition: 'Rainy' },
          { time: '12 PM', temp: 74, condition: 'Rainy' },
          { time: '3 PM', temp: 78, condition: 'Rainy' },
          { time: '6 PM', temp: 74, condition: 'Rainy' },
          { time: '9 PM', temp: 70, condition: 'Rainy' },
        ],
      },
      {
        date: '2025-04-13',
        maxTemp: 80,
        minTemp: 67,
        condition: 'Sunny',
        humidity: 55,
        windSpeed: 6,
        precipitation: 0,
        uvIndex: 7,
        hourly: [
          { time: '12 AM', temp: 69, condition: 'Partly cloudy' },
          { time: '3 AM', temp: 68, condition: 'Partly cloudy' },
          { time: '6 AM', temp: 67, condition: 'Partly cloudy' },
          { time: '9 AM', temp: 72, condition: 'Sunny' },
          { time: '12 PM', temp: 77, condition: 'Sunny' },
          { time: '3 PM', temp: 80, condition: 'Sunny' },
          { time: '6 PM', temp: 76, condition: 'Sunny' },
          { time: '9 PM', temp: 72, condition: 'Clear' },
        ],
      },
      {
        date: '2025-04-14',
        maxTemp: 82,
        minTemp: 68,
        condition: 'Hot',
        humidity: 50,
        windSpeed: 5,
        precipitation: 0,
        uvIndex: 8,
        hourly: [
          { time: '12 AM', temp: 70, condition: 'Clear' },
          { time: '3 AM', temp: 69, condition: 'Clear' },
          { time: '6 AM', temp: 68, condition: 'Clear' },
          { time: '9 AM', temp: 74, condition: 'Sunny' },
          { time: '12 PM', temp: 79, condition: 'Sunny' },
          { time: '3 PM', temp: 82, condition: 'Hot' },
          { time: '6 PM', temp: 78, condition: 'Sunny' },
          { time: '9 PM', temp: 73, condition: 'Clear' },
        ],
      },
      {
        date: '2025-04-15',
        maxTemp: 75,
        minTemp: 66,
        condition: 'Partly cloudy',
        humidity: 60,
        windSpeed: 9,
        precipitation: 10,
        uvIndex: 5,
        hourly: [
          { time: '12 AM', temp: 71, condition: 'Clear' },
          { time: '3 AM', temp: 69, condition: 'Clear' },
          { time: '6 AM', temp: 66, condition: 'Partly cloudy' },
          { time: '9 AM', temp: 70, condition: 'Partly cloudy' },
          { time: '12 PM', temp: 73, condition: 'Partly cloudy' },
          { time: '3 PM', temp: 75, condition: 'Partly cloudy' },
          { time: '6 PM', temp: 72, condition: 'Partly cloudy' },
          { time: '9 PM', temp: 69, condition: 'Partly cloudy' },
        ],
      },
      {
        date: '2025-04-16',
        maxTemp: 73,
        minTemp: 62,
        condition: 'Windy',
        humidity: 55,
        windSpeed: 15,
        precipitation: 5,
        uvIndex: 6,
        hourly: [
          { time: '12 AM', temp: 67, condition: 'Partly cloudy' },
          { time: '3 AM', temp: 65, condition: 'Partly cloudy' },
          { time: '6 AM', temp: 62, condition: 'Windy' },
          { time: '9 AM', temp: 66, condition: 'Windy' },
          { time: '12 PM', temp: 70, condition: 'Windy' },
          { time: '3 PM', temp: 73, condition: 'Windy' },
          { time: '6 PM', temp: 69, condition: 'Windy' },
          { time: '9 PM', temp: 65, condition: 'Windy' },
        ],
      },
    ],
  },
  history: {
    days: [
      { date: '2025-04-03', maxTemp: 68, minTemp: 57, precipitation: 0, windSpeed: 7 },
      { date: '2025-04-04', maxTemp: 70, minTemp: 59, precipitation: 0, windSpeed: 6 },
      { date: '2025-04-05', maxTemp: 72, minTemp: 60, precipitation: 5, windSpeed: 8 },
      { date: '2025-04-06', maxTemp: 73, minTemp: 61, precipitation: 15, windSpeed: 9 },
      { date: '2025-04-07', maxTemp: 69, minTemp: 58, precipitation: 60, windSpeed: 12 },
      { date: '2025-04-08', maxTemp: 67, minTemp: 56, precipitation: 45, windSpeed: 11 },
      { date: '2025-04-09', maxTemp: 71, minTemp: 60, precipitation: 10, windSpeed: 9 },
    ],
  },
};